### ISSUE TITLE
Information on the visibility of the form on all pages

### ISSUE THREAD

**Issue by bruno-rc** [pagantis/prestashop#80]
Can you tell me if it is possible to hide it from some categories of the site or id of the pages?
I have several products of a few euros and I wish it was not visible! Thank you

**Comment by pgarcess** [comment]
We can't hide by categories, anyway you can use the min. and max. amount to show/hide our simulator in your shop

**Comment by bruno-rc** [comment]
Hi, I just saw the answer now!
I made the modification from the database, but even if I changed the minimum value by putting example 100 it continues to be visible with lower amounts

**Comment by tmeliotpg** [comment]
Which version are you using please?

**Comment by bruno-rc** [comment]
Hello
Prestashop 1.7.6.4
Pagantis v8.6.7

**Comment by tmeliotpg** [comment]
Thank you, can you tell me how you changed the value in the database please.

**Comment by bruno-rc** [comment]
I have accessed my database
found ps_pagantis_config
and set DISPLAY_MIN_AMOUNT for example to 50 and I saved
I am attaching a demonstration photo
![esempio](https://user-images.githubusercontent.com/64578369/92372819-c58d8600-f0fd-11ea-8d05-e22aea6d158e.jpg)

**Comment by tmeliotpg** [comment]
Please provide the url of the store.

**Comment by bruno-rc** [comment]
https://www.apshoponline.it/

In the past, changing values in tpl
I changed the graphic aspect as you explained, now although they have been changed it no longer takes the new graphics I insert the modified files

[Onpageecheckouttpl.zip](https://github.com/pagantis/prestashop/files/5182337/Onpageecheckouttpl.zip)

**Comment by tmeliotpg** [comment]
It is not recommended editing this value directly in the database.

What exact minimum amount would you like to set on your store please ?

**Comment by bruno-rc** [comment]
Thanks I had read this from your guide!
Surely I will have misunderstood! I would like to set a minimum value of € 250 thanks

**Comment by tmeliotpg** [comment]
Please clear the store's cache and let me know when it's done

**Comment by bruno-rc** [comment]
ok cache emptied

**Comment by tmeliotpg** [comment]
Please check a product under 250€ and a product above 250€.
If it works please close the issue if it does not please let me know.
Regards

**Comment by bruno-rc** [comment]
Thanks now everything seems ok!
How can I maybe change the minimum fee in the future without disturbing you!
Regarding the graphic aspect, could you tell me why now despite the changes "that I have attached" are not visible
Thank you

**Comment by tmeliotpg** [comment]
Please email integrations@pagantis.com with this issue as reference and I will provide some explanations and possibly have a look at the onepagecheckout issue.

Regards

**Comment by bruno-rc** [comment]
OK thanks
