### ISSUE TITLE
Prevent "SHOW TABLES LIKE" in product page

### ISSUE THREAD

**Issue by crashncrow** [pagantis/prestashop#96]
Hi, 

there is any chance to prevent running the query "SHOW TABLES LIKE..." every time someone access to a product page?

https://github.com/pagantis/prestashop/blob/9f6e4cd1f0a8ca06de92e480b81be8d793486100/pagantis.php#L288

Thanks in advance!

**Comment by rmarinleal** [comment]
Hi, 

One the module is installed, you can clean this function code. Unfortunatelly Prestashop don't have an update method to allow us to know it the merchant have installed the module from scratch or if it's an update from an old version and we must prevent DB changes if you came form an old version.

But you're right and you can improve the module perfomance if you delete the code of **loadSQLFile** method and only leave a _return true;_ line once you have the module installed

`
    public function loadSQLFile($sql_file)
    {
         return true;
    }
`

Best regards

**Comment by crashncrow** [comment]
Hi, 

maybe it's a good idea to run this code only in back office context:

`$current_context = Context::getContext();`

`if ($current_context->controller->controller_type != 'front'){`
`    // loadSQLFile queries`
`}`

Regards!

**Comment by rmarinleal** [comment]
Hi @crashncrow, we're going to tests your solution and if it's valid we'll implement and release it.

Thank you very much for your feedback!

**Comment by rmarinleal** [comment]
@crashncrow The solution works but we addedd another validation in order to prevent Warnings/Errors when current_context->controller is null

We're going to refactor the code on the main file (pagantis.php) and prevent executions of:

```
$current_context = Context::getContext();
        if (!is_null($current_context->controller) && $current_context->controller->controller_type != 'front') {
            $sql_file = dirname(__FILE__).'/sql/install.sql';
            $this->loadSQLFile($sql_file);
            $this->checkEnvVariables();
            $this->migrate();
            $this->checkHooks();
            $this->checkPromotionCategory();
        }
```

It'll available in the next release 

Best regards.
